### ISSUE TITLE
Minerva PyPi upload fails for Python 2 due to non-ASCII character in generated __init__.py

### ISSUE THREAD

**Issue by mithro** [litex-hub/pythondata-auto#12]
https://github.com/litex-hub/pythondata-cpu-minerva/runs/3807598286?check_suite_focus=true
```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from pythondata_cpu_minerva import version_str
  File "/home/runner/work/pythondata-cpu-minerva/pythondata-cpu-minerva/pythondata_cpu_minerva/__init__.py", line 27
SyntaxError: Non-ASCII character '\xc3' in file /home/runner/work/pythondata-cpu-minerva/pythondata-cpu-minerva/pythondata_cpu_minerva/__init__.py on line 28, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Error: Process completed with exit code 1.
```

**Comment by mithro** [comment]
Python 2 support has been dropped.
