### ISSUE TITLE
ValueError: invalid interpolation syntax in XXX

### ISSUE THREAD

**Issue by mithro** [litex-hub/pythondata-auto#22]
```
ibex Config
ibex

Cloning into bare repository 'srcs/pythondata-misc-opentitan'...
Traceback (most recent call last):
  File "./update.py", line 588, in <module>
    sys.exit(main(sys.argv[0], sys.argv[1:]))
  File "./update.py", line 540, in main
    get_src(m)
  File "./update.py", line 210, in get_src
    module_data['git_msg'] = git_msg
  File "/usr/lib/python3.6/configparser.py", line 1238, in __setitem__
    return self._parser.set(self._name, key, value)
  File "/usr/lib/python3.6/configparser.py", line 1193, in set
    super().set(section, option, value)
  File "/usr/lib/python3.6/configparser.py", line 894, in set
    value)
  File "/usr/lib/python3.6/configparser.py", line 402, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'commit b209267af8a08ffc34879ecd3fb88e38f165cd63\nAuthor: Srikrishna Iyer <sriyer@google.com>\nDate:   Tue Oct 12 15:54:00 2021 -0700\n\n    [dv, clk_rst_if] Improve jitter and add scaling\n    \n    - Cleanup existing code / comments\n    - Replace `ifdef VERILATOR` with existing macros\n    - Add support for randomly scaling the frequency on each edge with +-\n    %tage over the initially set frequency\n    - Improve jitter generation - use `$urandom` instead of\n    `std::randomize`.\n    - Fix jitter generation bug where the originally set clk hi and lo half\n    periods get modified\n    \n    Signed-off-by: Srikrishna Iyer <sriyer@google.com>\n' at position 359
Error: Process completed with exit code 1.
```

**Comment by mithro** [comment]
Should have been fixed by #33
