### ISSUE TITLE
GitHub Actions is failing and needs fixing due to picolibc issue

### ISSUE THREAD

**Issue by mithro** [litex-hub/pythondata-auto#36]
https://github.com/litex-hub/pythondata-auto/actions/runs/3222070562/jobs/5270739391
```
picolibc Updating

picolibc Config
picolibc Details
  picolibc 1.7.8.post528 (1, 7, 8, 528)
  Tools: 0.0.post142 (0, 0, 142)
   Data: 1.7.8.post386 (1, 7, 8, 386)
  Updating repo  litex-hub/pythondata-software-picolibc
  404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#update-a-repository"}
  Cloning into 'repos/pythondata-software-picolibc'...
  Submodule 'pythondata_software_picolibc/data' (https://github.com/picolibc/picolibc) registered for path 'pythondata_software_picolibc/data'
  Cloning into '/home/runner/work/pythondata-auto/pythondata-auto/repos/pythondata-software-picolibc/pythondata_software_picolibc/data'...
  fatal: remote error: upload-pack: not our ref 580d4f13de47a3eaf66f10cfc8537721b21dfc31
  fatal: Fetched in submodule path 'pythondata_software_picolibc/data', but it did not contain 580d4f13de47a3eaf66f10cfc8537721b21dfc31. Direct fetching of that commit failed.
  Traceback (most recent call last):
    File "./update.py", line 677, in <module>
      sys.exit(main(sys.argv[0], sys.argv[1:]))
    File "./update.py", line 652, in main
      download(m)
    File "./update.py", line 84, in download
      subprocess_check_call(cmd.split())
    File "./update.py", line 27, in subprocess_check_call
      return subprocess.check_call(*args, **kw)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['git', 'clone', '--recursive', 'https://github.com/litex-hub/pythondata-software-picolibc.git', 'repos/pythondata-software-picolibc']' returned non-zero exit status 128.
  Error: Process completed with exit code 1.
```

**Comment by mithro** [comment]
See also;
 * https://github.com/enjoy-digital/litex/issues/1457
 * https://github.com/litex-hub/pythondata-software-picolibc/commit/bfa87fc1a0493aa8d97d855dae7f843966dee672#commitcomment-86369008

**Comment by mithro** [comment]
@kgugala - Could you get someone at Antmicro to take a look at this?

**Comment by kgugala** [comment]
this is fixed now
