### ISSUE TITLE
Autopush broken due to conversion from master to main on some upstream repos

### ISSUE THREAD

**Issue by mithro** [litex-hub/pythondata-auto#8]
```
Cloning into bare repository 'srcs/pythondata-cpu-serv'...
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "./update.py", line 559, in <module>
    sys.exit(main(sys.argv[0], sys.argv[1:]))
  File "./update.py", line 511, in main
    get_src(m)
  File "./update.py", line 193, in get_src
    git_hash = get_hash(module_data['branch'], env)
  File "./update.py", line 125, in get_hash
    env=env).decode('utf-8').strip()
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'master']' returned non-zero exit status 128.
Error: Process completed with exit code 1.
```

**Comment by enjoy-digital** [comment]
@mithro Can you have a look at fixing `pythondata-auto` or have someone looking at it? The initial aim for it was to simplify creating/updating external data files but the fact that it's not often functional complicates maintenance. Thanks.

**Comment by mithro** [comment]
@kgugala - Can you get someone to look at this?

**Comment by mithro** [comment]
@enjoy-digital - I do apologize and agree that it isn't acceptable for this to be broken since June 9th and nobody fixing it.
